"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-24 12:42:03.623940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=True),
    sa.Column('rg', sa.String(length=20), nullable=True),
    sa.Column('cpf', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('telefone', sa.String(length=30), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('nacionalidade', sa.String(length=80), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('profissao', sa.String(length=120), nullable=True),
    sa.Column('perfil_completo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imoveis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locador_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('bairro', sa.String(length=120), nullable=False),
    sa.Column('cidade', sa.String(length=120), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=9), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locador_id'], ['locadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contratos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imovel_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('duracao_contrato', sa.String(length=50), nullable=False),
    sa.Column('data_inicio', sa.Date(), nullable=False),
    sa.Column('data_termino', sa.Date(), nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=120), nullable=False),
    sa.Column('nome_locatario', sa.String(length=200), nullable=True),
    sa.Column('rg_locatario', sa.String(length=20), nullable=True),
    sa.Column('cpf_locatario', sa.String(length=20), nullable=True),
    sa.Column('email_locatario', sa.String(length=200), nullable=True),
    sa.Column('telefone_locatario', sa.String(length=30), nullable=True),
    sa.Column('endereco_locatario', sa.String(length=255), nullable=True),
    sa.Column('nacionalidade_locatario', sa.String(length=80), nullable=True),
    sa.Column('estado_locatario', sa.String(length=50), nullable=True),
    sa.Column('profissao_locatario', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('filled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['imovel_id'], ['imoveis.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('assinaturas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contrato_id', sa.Integer(), nullable=False),
    sa.Column('papel', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('hash_documento', sa.String(length=64), nullable=False),
    sa.Column('assinado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['contrato_id'], ['contratos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assinaturas')
    op.drop_table('contratos')
    op.drop_table('imoveis')
    op.drop_table('login_attempts')
    op.drop_table('locadores')
    # ### end Alembic commands ###
